from enum import Enum


class MapAmenity(Enum):
    SUSTENANCE_BAR = 0
    SUSTENANCE_CAFE = 1
    SUSTENANCE_FASTFOOD = 2
    SUSTENANCE_FOODCOURT = 3
    SUSTENANCE_PUB = 4
    SUSTENANCE_RESTAURANT = 5

    EDUCATION_COLLEGE = 6
    EDUCATION_DRIVINGSCHOOL = 7
    EDUCATION_LANGUAGESCHOOL = 8
    EDUCATION_LIBRARY = 9
    EDUCATION_TRAINING = 10
    EDUCATION_MUSICSCHOOL = 11
    EDUCATION_SCHOOL = 12
    EDUCATION_UNIVERSITY = 13

    TRANSPORTATION_BICYCLERENTAL = 14
    TRANSPORTATION_CARRENTAL = 15
    TRANSPORTATION_CARWASH = 16
    TRANSPORTATION_FUEL = 17
    TRANSPORTATION_PARKING = 18
    TRANSPORTATION_TAXI = 19

    FINANCIAL_BANK = 20

    HEALTHCARE_CLINIC = 21
    HEALTHCARE_DENTIST = 22
    HEALTHCARE_DOCTORS = 23
    HEALTHCARE_HOSPITAL = 24
    HEALTHCARE_PHARMANCY = 25
    HEALTHCARE_VETERINARY = 26

    ENTERTAINMENT_ARTSCENTER = 27
    ENTERTAINMENT_BROTHEL = 28          # KEK
    ENTERTAINMENT_CASINO = 29
    ENTERTAINMENT_CINEMA = 30
    ENTERTAINMENT_CONFERENCECENTER = 31
    ENTERTAINMENT_FOUNTAIN = 32
    ENTERTAINMENT_NIGHTCLUB = 33
    ENTERTAINMENT_PLANETARIUM = 34
    ENTERTAINMENT_SOCIALCENTER = 35
    ENTERTAINMENT_STRIPCLUB = 36        # KEK x2
    ENTERTAINMENT_STUDIO = 37
    ENTERTAINMENT_THEATRE = 38

    PUBLIC_COURTHOUSE = 39
    PUBLIC_FIRESTATION = 40
    PUBLIC_POLICE = 41
    PUBLIC_PRISON = 42

    OTHERS_MARKETPLACE = 43
    OTHERS_PLASEOFWORSHIP = 44


class MapBulding(Enum):
    RELIGIOUS_CATHEDRAL = 0
    RELIGIOUS_CHAPEL = 1
    RELIGIOUS_CHUCRH = 2
    RELIGIOUS_MONASTERY = 3
    RELIGIOUS_SYNAGOGE = 4
    RELIGIOUS_TEMPLE = 5

    SPORTS_GRANDSTAND = 6
    SPORTS_PAVILION = 7
    SPORTS_SPORTSHALL = 8
    SPORTS_STADIUM = 9


class MapObjects(Enum):
    AMENITY = 0
    SHOP = 1
    SUBWAY = 2
    TOURISM = 3

QueryMapping = {
    MapObjects.AMENITY : 'amenity',
    MapObjects.SHOP : 'shop',
    MapObjects.SUBWAY : 'station',
    MapObjects.TOURISM : 'tourism'
}
